version: "3.8"

services:

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9090"
    container_name: minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio:/data
    networks:
      - my-network

  appcode:
    image: challenge1_app
    build: .
    volumes:
      - core:/code/core
    container_name: challenge1_backend
    ports:
      - "4000:7000"
    networks:
      - my-network
    depends_on:
      - minio
  

volumes:
  core:
    driver: local
  
  minio:
    driver: local

networks:
   my-network:
     driver: bridge